package com.buruhkoding.mithrilhammer;

import java.util.ArrayList;

public class HeroData {
    public static String[][] data = new String[][] {
            {"1", "Doom", "Lucifer, the Doom", "Meele", "Strength", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/4/40/Doom_icon.png?version=73fd5dbb42fd25b8c7f99bdabe240865", "He that burns and is not consumed, devours and is never sated, kills and is beyond all judgment--Lucifer brings doom to all who would stand against him. Bearing away souls on the tip of a fiery sword, he is the Fallen One, a once-favored general from the realm behind the light, cast out for the sin of defiance: he would not kneel. Six times his name was tolled from the great bell of Vashundol. Six and sixty times his wings were branded, until only smoking stumps remained. Without wings, he slipped loose from the tethers that bound him within the light and he fell screaming to earth. A crater in the desert, Paradise lost. Now he attacks without mercy, without motive, the only living being able to move freely between the seven dark dominions. Lashed by inescapable needs, twisted by unimaginable talents, Doom carries his own hell with him wherever he goes. Defiant to the last. Eventually, the world will belong to Doom.", "200", "27-43", "-1", "280", "26", "11", "15", "Devour", "Scorched Earth", "Infernal Blade", "Doom"},
            {"2", "Morphling", "Morphling", "Range", "Agility", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/7/7b/Morphling_icon.png?version=e3fb6a35e9420dff83b5bcf3015a816c", "For dark eons the comet circled. Held in thrall to a distant sun, bound by gravity’s inexorable pull, the massive ball of ice careened through the blackness between worlds, made strange by its dark journey. On the eve of the ancient war of the Vloy, it punched down through the sky and lit a glowing trail across the night, a sign both armies took for an omen. The frozen ball melted in a flash of boiling heat, as below two forces enjoined in battle across the border of a narrow river. Thus freed from its icy stasis, the Morphling was born into conflict, an elemental power at one with the tides of the ocean, capricious and unconstrained. He entered the fight, instinctively taking the form of the first general who dared set foot across the water, and then struck him dead. As the motley warriors clashed, he shifted from form to form throughout the battle, instantly absorbing the ways of these strange creatures--now a footsoldier, now an archer, now the cavalryman--until, by the time the last soldier fell, Morphling had played every part. The battle's end was his beginning.", "200", "9-18", "280", "20", "24", "13", "Waveform", "Adaptive Strike", "Attribute Shift", "Morph"},
            {"3", "Bane", "Atropos the Bane Elemental", "Range", "Intelegence", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/c/c3/Bane_icon.png?version=04e7a3716b6bdb461db5d4c5b37bb62c", "When the gods have nightmares, it is Bane Elemental who brings them. Also known as Atropos, Bane was born from the midnight terrors of the goddess Nyctasha. A force of terror too powerful to be contained by sleep, he surfaced from her slumbers, fed upon her immortality, and stole his vaporous form from her inky blood. He is the essence of fear. Mortals who hear his voice hear their darkest secrets whispered in their ear. He calls to the hidden fear in every Hero's heart. Wakefulness is no protection, for Bane's black blood, continuously dripping, is a tar that traps his enemies in nightmare. In the presence of Bane, every Hero remembers to fear the dark.", "200", "35-41", "310", "23", "23", "23", "Enfeeble", "Brain Sap", "Nightmare", "Fiend's Grip"},
            {"4", "Meepo", "Meepo the Geomancer", "Meele", "Agility", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/8/85/Meepo_icon.png?version=f1153c6a49336b34158d76bac3bf2940", "If you ask me, life is all about who you know and what you can find. When you live up in the Riftshadow Ruins, just finding food can be tough. So you need to cut corners, you need to scrounge, you need to know your strengths. Some of the beasts up there can kill you, so you need a way to trap the weak and duck the strong. On the upside, the ruins have history, and history is worth a lot to some people. There used to be a palace there, where they had all these dark rituals. Bad stuff. If you survived the ceremony, they would shatter a crystal and split your soul into pieces. They made great art though! Sculptures and such. Let me tell you: sometimes you stumble onto some of those old carvings. Take a pack full of those to town and sell them, then get yourself food for a few weeks. If luck is really on your side, you might find a Riftshadow crystal. Get it appraised and start asking around. Someone always knows some crazy fool looking for this kind of thing. If all else fails, sell it to a Magus the next time one's in town. They love that stuff. Still, whatever you do, be careful handling those crystals. You do not want one to go off on you. It really hurts.", "200", "20-26", "310", "24", "23", "20", "Earthbind", "Poof", "Geostrike", "Divided We Stand"},
            {"5", "Kunkka", "Kunkka the Admiral", "Meele", "Strength", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/c/c0/Kunkka_icon.png?version=978988169230c181a0f02331888cf84f", "As Admiral of the mighty Claddish Navy, Kunkka was charged with protecting the isles of his homeland when the Demons of the Cataract made a concerted grab at the lands of men. After years of small sorties, and increasingly bold and devastating attacks, the Demon Fleet flung all its carnivorous ships at the Trembling Isle. Desperate, the Suicide-Mages of Cladd committed their ultimate rite, summoning a host of ancestral spirits to protect the fleet. Against the Demons, this was just barely enough to turn the tide. As Kunkka watched the Demons take his ships down one by one, he had the satisfaction of wearing away their fleet with his ancestral magic. But at the battle's peak, something in the clash of demons, men and atavistic spirits must have stirred a fourth power that had been slumbering in the depths. The waves rose up in towering spouts around the few remaining ships, and Maelrawn the Tentacular appeared amid the fray. His tendrils wove among the ships, drawing demon and human craft together, churning the water and wind into a raging chaos. What happened in the crucible of that storm, none may truly say. The Cataract roars off into the void, deserted by its former denizens. Kunkka is now Admiral of but one ship, a ghostly rig which endlessly replays the final seconds of its destruction. Whether he died in that crash is anyone's guess. Not even Tidehunter, who summoned Maelrawn, knows for sure.", "200", "26-36", "295", "24", "14", "18", "Torrent", "Tidebringer", "X Marks the Spot", "Ghostship"},
            {"6", "Shadow Fiend", "Nevermore the Shadow Fiend", "Range", "Agility", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/3/36/Shadow_Fiend_icon.png?version=ca3e0093887116c08f929aa99700ae4d", "It is said that Nevermore the Shadow Fiend has the soul of a poet, and in fact he has thousands of them. Over the ages he has claimed the souls of poets, priests, emperors, beggars, slaves, philosophers, criminals and (naturally) heroes; no sort of soul escapes him. What he does with them is unknown. No one has ever peered into the Abysm whence Nevermore reaches out like an eel from among astral rocks. Does he devour them one after another? Does he mount them along the halls of an eldritch temple, or pickle the souls in necromantic brine? Is he merely a puppet, pushed through the dimensional rift by a demonic puppeteer? Such is his evil, so intense his aura of darkness, that no rational mind may penetrate it. Of course, if you really want to know where the stolen souls go, there's one sure way to find out: Add your soul to his collection. Or just wait for Nevermore.", "200", "15-21", "310", "16", "20", "18", "Shadowraze", "Necromastery", "Presence of The Dark Lord", "Requiem of Souls"},
            {"7", "Puck", "Puck the Faerie Dragon", "Range", "Intelegence", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/1/13/Puck_icon.png?version=5d87685f13984ed6aeb8b38aca9c4c64", "While Puck seems at first glance a mischievous, childish character, this quality masks an alien personality. The juvenile form of a Faerie Dragon, a creature that lives for eons, Puck spends countless millennia in its childish form. So while it is technically true that Puck is juvenile, it will continue to be so when the cities of the present age have sloughed away into dust. Its motives are therefore inscrutable, and what appears to be play may in fact indicate a darker purpose or just its endless fondness for mischief.", "200", "30-41", "295", "17", "22", "23", "Illusory Orb", "Warning Rift", "Phase Shift", "Dream Coil"},
            {"8", "Visage", "Visage the Bound Form of Necro'lic", "Range", "Intelegence", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/9/9e/Visage_icon.png?version=e87aa565648e5978b6052a60bc0fa3e9", "Perched atop the entrance to the Narrow Maze sit the looming shapes of sneering gargoyles, the paths into the hereafter forever in their gaze. Beasts and birds, men and monsters, all creatures that die and choose to travel beyond must someday pass beneath their sight. For an untethered spirit, the decision to journey through the veil of death is irrevocable. When chance comes, and by craft or cunning some restless soul escapes their hells and heavens, it is the dreaded gargoyle Visage, the bound form of the eternal spirit Necro’lic, who is dispatched to reclaim them. Ruthless and efficient, unhindered by the principles of death and fatigue, Visage stalks its prey without mercy or end, willingly destroying all which may give shelter to the fugitive essence. That which flaunts the laws of the afterlife may never rest, for while it is true that the dead may be revived, it is only a matter of time before Visage finds and returns them to their proper place.", "200", "23-33", "285", "24", "11", "22", "Grave Chill", "Soul Assumption", "Gravekeeper's Cloak", "Summon Familiars"},
            {"9", "Enchantress", "Aiushtha the Enchantress", "Range", "Intelegence", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/4/41/Enchantress_icon.png?version=ff9dcd9f63e1eddf16b9b31317232235", "Aiushtha appears to be an innocent, carefree creature of the woods, and while this is certainly true, it is hardly the sum of her story. She well understands the suffering of the natural world. She has wandered far, and fared through forests bright and drear, in every clime and every season, gathering friends, sharing news, bringing laughter and healing wherever she goes. For in worlds wracked by war, forests are leveled for the building of ships and siege engines; and even in places of peace, the woods are stripped for the building of homes, and as fuel for countless hearths. Aiushtha hears the pleas of the small creatures, the furtive folk who need green shade and a leafy canopy to thrive. She lends her ears to those who have no other listeners. She carries their stories from the wood to the world, believing that her own good cheer is a kind of Enchantment, that can itself fulfill the promise of a verdant future.", "200", "30-40", "320", "16", "19", "17", "Untouchable", "Enchant", "Nature's Attendants", "Impetus"},
            {"10", "Ember Spirit", "Xin the Ember Spirit", "Meele", "Strength", "https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/9/91/Ember_Spirit_icon.png?version=03f2bf4e5fc2e5f1e926e43d6ff53eec", "Lost within the Wailing Mountains, the Fortress of Flares lay abandoned, its training halls empty, its courtyard covered in leaves and dust. Upon a dais in its sealed temple rests a topaz cauldron filled with ancient ash, remnants of a pyre for the warrior-poet Xin. For three generations, Xin taught his acolytes the Bonds of the Guardian Flame, a series of mantras to train the mind and body for the harsh realities beyond the fortress walls. However, in teaching a warrior's way he earned a warrior's rivals, and in his autumn Xin was bested and slain. His followers spread to the wind. Yet as years turned to centuries and followers to descendants, his teachings endured by subtle whisper and deed. Touched by the teacher's lasting legacy, the Burning Celestial, inquisitive aspect of fire, cast himself to the Fortress of Flares and reignited the pyre ash. From these glowing embers emerged an image of Xin, wreathed in flame, his thoughtful countenance prepared to train and to teach, and to spread the fires of knowledge to all who seek guidance.", "200", "30-34", "305", "20", "22", "20", "Searing Chains", "Sleight of Fist", "Flame Guard", "Fire Remnant"},
    };

    public static ArrayList<Hero> getListData() {
        Hero hero = null;
        ArrayList<Hero> list = new ArrayList<>();

        for (int i = 0; i < data.length; i++){
            hero = new Hero();
            hero.setId(Integer.parseInt(data[i][0]));
            hero.setName(data[i][1]);
            hero.setTitle(data[i][2]);
            hero.setImage(data[i][5]);

            list.add(hero);
        }

        return list;
    }

    public static Hero getHeroDetail(int position) {
        Hero hero = null;

        for (int i = 1; i <= data.length; i++){
            if (i == position) {
                int flag = i - 1;
                hero = new Hero();
                hero.setName(data[flag][1]);
                hero.setTitle(data[flag][2]);
                hero.setType(data[flag][3]);
                hero.setTop_attribute(data[flag][4]);
                hero.setImage(data[flag][5]);
                hero.setLore(data[flag][6]);
//                hero.setBase_health(data[i][7]);
//                hero.setBase_damage(data[i][8]);
//                hero.setBase_armor(data[i][9]);
//                hero.setMovement_speed(data[i][10]);
//                hero.setBase_str(data[i][11]);
//                hero.setBase_agi(data[i][12]);
//                hero.setBase_int(data[i][13]);
//                hero.setFirst_ability(data[i][14]);
//                hero.setSecond_ability(data[i][15]);
//                hero.setThird_ability(data[i][16]);
//                hero.setUltimate_ability(data[i][17]);
            }
        }

        return hero;
    }

}
